### ISSUE TITLE
electron main 中使用axios报错  XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by kirahan** [electron-vite/vite-plugin-electron-quick-start#1]
不知道为什么这个模板中没法在主进程中用axios, 参考代码
# electron-main/index.ts

import axios from 'axios'

app.whenReady().then(()=>{
  createWindow()
  setTimeout(()=>{
    axios.get('http://api.m.taobao.com/rest/api3.do?api=mtop.common.getTimestamp').then(data=>{console.log('time',data)})
  },2000)
})

UnhandledPromiseRejectionWarning: ReferenceError: XMLHttpRequest is not defined
    at dispatchXhrRequest

**Comment by caoxiemeihao** [comment]
https://github.com/axios/axios/issues/552#issuecomment-267042832

```js
axios
  .create({ adapter: require('axios/lib/adapters/http') })
  .get('http://api.m.taobao.com/rest/api3.do?api=mtop.common.getTimestamp')
  .then(data => { console.log('time', data) })
```
