### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by setli** [electron-vite/vite-plugin-electron-quick-start#2]
![image](https://user-images.githubusercontent.com/19206807/172431878-3ef6abb3-bc61-4229-94d4-0738adae10d0.png)

**Comment by caoxiemeihao** [comment]
What is your `vite-plugin-electron` version? The BUG come may from `v0.4.7`.

**Comment by setli** [comment]
> Thank you for the response 
"vite-plugin-electron": "^0.4.5"

**Comment by caoxiemeihao** [comment]
Now, you can try to pull the latest code.

**Comment by setli** [comment]
> Now, you can try to pull the latest code.

👍 Thanks
