### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by benjenpoetry** [electron-vite/vite-plugin-electron-quick-start#3]
![image](https://user-images.githubusercontent.com/101650854/172562939-2cf4376f-47b5-41f3-8530-5d86d8f92de2.png)

**Comment by caoxiemeihao** [comment]
You can try to configure Electron mirror in `.npmrc` for resolve the Network problem.

**e.g.**

*In your `.npmrc`*

```config
electron-mirror=https://npm.taobao.org/mirrors/electron/
```

**Comment by benjenpoetry** [comment]
设置之后已经可用了，thanks
