### ISSUE TITLE
How to disable electron to open in `yarn dev`

### ISSUE THREAD

**Issue by patrickelectric** [electron-vite/vite-plugin-electron-quick-start#4]
Hi, I want to use a web browser to display the website over an eletron app, is that possible ?
Running `yarn dev` as normal without a new window running electron.

**Comment by caoxiemeihao** [comment]
You can see 👉 [Custom start Electron](https://github.com/electron-vite/vite-plugin-electron/tree/main/packages/electron#custom-start-electron)

```ts
import electron, { onstart } from 'vite-plugin-electron'

export default {
  plugins: [
    electron({
      main: {
        entry: 'electron/main/index.ts',
        vite: {
          plugins: [
            onstart(() => {
              // Custom start Electron here!
            }),
          ],
        },
      },
    }),
  ],
}
```
